name: receptyUser
description: Flutter Starter” --org com.alcubix.receptyUser”
version: 1.0.1+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  dio: ^4.0.6
  connectivity_plus: ^2.3.7
  get_it: ^7.2.0
  injectable: ^1.5.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.0
  dartz: ^0.10.1
  flutter_svg: ^1.0.3
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.5.3+2
  sms_autofill: ^2.2.0
  shared_preferences: ^2.0.13
  easy_localization: ^3.0.1
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.1
  new_version: ^0.3.0
  file_picker: ^5.2.5
  dotted_border: ^2.0.0+3
  image_picker: ^0.8.6+1
  flutter_image_compress: ^1.1.3
  mime: ^1.0.4
  flutter_staggered_grid_view: ^0.6.2
  iconly:
  flutter_launcher_icons: ^0.11.0
  numberpicker: ^2.1.1
  video_player: ^2.5.2
  photo_gallery: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  # add the generator to your dev_dependencies
  injectable_generator:
  build_runner:


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/recepty_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/1.5x/
    - assets/images/0.75x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/
    - assets/icons/
    - assets/translations/
